DELETE FROM content_tags_list;
DELETE FROM content;
DELETE FROM tag_alias;
DELETE FROM tag;

ALTER TABLE content AUTO_INCREMENT = 0;
ALTER TABLE tag_alias AUTO_INCREMENT = 0;
ALTER TABLE tag AUTO_INCREMENT = 0;